#!/bin/sh

echo "Gofmt Hook"
echo "----------"



STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

[ -z "$STAGED_GO_FILES" ] && echo "No Go Files to Update" 

 for file in $STAGED_GO_FILES; do
        go fmt $file
        git add $file
    done
