#!/bin/sh

echo "Gofmt Hook"
echo "----------"



STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

if [ -z "$STAGED_GO_FILES" ];then 
        echo "No Go Files to Update"; 
else
 for file in $STAGED_GO_FILES; do
        go fmt "$file";
        git add "$file";
    done;
fi
